name: Update Cloudflare Best IP

on:
  schedule:
    - cron: "0 4,16 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TZ: Asia/Shanghai
    
    permissions:
      contents: write
      actions: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate bestcf `IP`
        run: |
          mkdir -p ./bestcf/
          # CMCC-IP
          curl -sSL https://cf.090227.xyz/cmcc | sed 's/#.*//' | awk '{print $0 "#CMCC-IPv4_CMLiu"}' > ./bestcf/cmcc-ip.txt
          curl -sSL https://cf.090227.xyz/cmcc-ipv6 | sed 's/#.*//' | awk '{print $0 "#CMCC-IPv6_CMLiu"}' >> ./bestcf/cmcc-ip.txt
          curl -sSL https://vps789.com/openApi/cfIpApi | jq -r '.data.CM[].ip' | awk '{print $0 "#CMCC-IPv4_VPS789"}' >> ./bestcf/cmcc-ip.txt
          curl -sSL https://api.hostmonit.com/get_optimization_ip --data-raw '{"key":"iDetkOys"}' | jq -r '.info[] | select(.line == "CM") | .ip' | awk '{print $0 "#CMCC-IPv4_CFYes"}' >> ./bestcf/cmcc-ip.txt
          curl -sSL https://api.hostmonit.com/get_optimization_ip --data-raw '{"key":"iDetkOys","type":"v6"}' | jq -r '.info[] | select(.line == "CM") | .ip' | awk '{print "["$0"]#CMCC-IPv6_CFYes"}' >> ./bestcf/cmcc-ip.txt
          curl -sSL https://www.wetest.vip/page/cloudflare/address_v4.html | awk '/移动/{getline; print}' | awk -F '[<>]' '{print $3}' | awk '{print $0 "#CMCC-IPv4_WeTest"}' >> ./bestcf/cmcc-ip.txt
          curl -sSL https://www.wetest.vip/page/cloudflare/address_v6.html | awk '/移动/{getline; print}' | awk -F '[<>]' '{print $3}' | awk '{print "["$0"]#CMCC-IPv6_WeTest"}' >> ./bestcf/cmcc-ip.txt

          # CUCC-IP
          curl -sSL https://cf.090227.xyz/cu | sed 's/#.*//' | awk '{print $0 "#CUCC-IPv4_CMLiu"}' > ./bestcf/cucc-ip.txt
          curl -sSL https://vps789.com/openApi/cfIpApi | jq -r '.data.CU[].ip' | awk '{print $0 "#CUCC-IPv4_VPS789"}' >> ./bestcf/cucc-ip.txt
          curl -sSL https://api.hostmonit.com/get_optimization_ip --data-raw '{"key":"iDetkOys"}' | jq -r '.info[] | select(.line == "CU") | .ip' | awk '{print $0 "#CUCC-IPv4_CFYes"}' >> ./bestcf/cucc-ip.txt
          curl -sSL https://api.hostmonit.com/get_optimization_ip --data-raw '{"key":"iDetkOys","type":"v6"}' | jq -r '.info[] | select(.line == "CU") | .ip' | awk '{print "["$0"]#CUCC-IPv6_CFYes"}' >> ./bestcf/cucc-ip.txt
          curl -sSL https://www.wetest.vip/page/cloudflare/address_v4.html | awk '/联通/{getline; print}' | awk -F '[<>]' '{print $3}' | awk '{print $0 "#CUCC-IPv4_WeTest"}' >> ./bestcf/cucc-ip.txt
          curl -sSL https://www.wetest.vip/page/cloudflare/address_v6.html | awk '/联通/{getline; print}' | awk -F '[<>]' '{print $3}' | awk '{print "["$0"]#CUCC-IPv6_WeTest"}' >> ./bestcf/cucc-ip.txt

          # CTCC-IP
          curl -sSL https://cf.090227.xyz/ct | sed 's/#.*//' | awk '{print $0 "#CTCC-IPv4_CMLiu"}' > ./bestcf/ctcc-ip.txt
          curl -sSL https://vps789.com/openApi/cfIpApi | jq -r '.data.CT[].ip' | awk '{print $0 "#CTCC-IPv4_VPS789"}' >> ./bestcf/ctcc-ip.txt
          curl -sSL https://api.hostmonit.com/get_optimization_ip --data-raw '{"key":"iDetkOys"}' | jq -r '.info[] | select(.line == "CT") | .ip' | awk '{print $0 "#CTCC-IPv4_CFYes"}' >> ./bestcf/ctcc-ip.txt
          curl -sSL https://api.hostmonit.com/get_optimization_ip --data-raw '{"key":"iDetkOys","type":"v6"}' | jq -r '.info[] | select(.line == "CT") | .ip' | awk '{print "["$0"]#CTCC-IPv6_CFYes"}' >> ./bestcf/ctcc-ip.txt
          curl -sSL https://www.wetest.vip/page/cloudflare/address_v4.html | awk '/电信/{getline; print}' | awk -F '[<>]' '{print $3}' | awk '{print $0 "#CTCC-IPv4_WeTest"}' >> ./bestcf/ctcc-ip.txt
          curl -sSL https://www.wetest.vip/page/cloudflare/address_v6.html | awk '/电信/{getline; print}' | awk -F '[<>]' '{print $3}' | awk '{print "["$0"]#CTCC-IPv6_WeTest"}' >> ./bestcf/ctcc-ip.txt

      - name: Git push to main branch
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bestcf/cmcc-ip.txt bestcf/cucc-ip.txt bestcf/ctcc-ip.txt
          git commit -m "Auto update Bestip: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push origin main

      - name: Delete releases and workflows runs
        uses: ophub/delete-releases-workflows@main
        with:
          delete_releases: false
          releases_keep_latest: 10
          delete_workflows: true
          workflows_keep_day: 1
          gh_token: ${{ secrets.GITHUB_TOKEN }}
